mohtat2020 = {
    "citations": ["Mohtat2020"],
    "Ambient temperature [K]": 298.15,
    "Boltzmann constant [J.K-1]": 1.380649e-23,
    "Bulk solvent concentration [mol.m-3]": 2636.0,
    "Cation transference number": 0.38,
    "Cell cooling surface area [m2]": 0.41,
    "Cell volume [m3]": 3.92e-05,
    "Contact resistance [Ohm]": 0,
    "Current function [A]": 5.0,
    "EC diffusivity [m2.s-1]": 2e-18,
    "EC initial concentration in electrolyte [mol.m-3]": 4541.0,
    "Edge heat transfer coefficient [W.m-2.K-1]": 5.0,
    "Electrode height [m]": 1.0,
    "Electrode width [m]": 0.205,
    "Electron charge [C]": 1.602176634e-19,
    "Exchange-current density for plating [A.m-2]": 0.001,
    "Faraday constant [C.mol-1]": 96485.33212,
    "Ideal gas constant [J.K-1.mol-1]": 8.314462618,
    "Initial concentration in electrolyte [mol.m-3]": 1000.0,
    "Initial concentration in negative electrode [mol.m-3]": 48.8682,
    "Initial concentration in positive electrode [mol.m-3]": 31513.0,
    "Initial inner SEI thickness [m]": 2.5e-09,
    "Initial outer SEI thickness [m]": 2.5e-09,
    "Initial plated lithium concentration [mol.m-3]": 0.0,
    "Initial temperature [K]": 298.15,
    "Inner SEI electron conductivity [S.m-1]": 8.95e-14,
    "Inner SEI lithium interstitial diffusivity [m2.s-1]": 1e-20,
    "Inner SEI open-circuit potential [V]": 0.1,
    "Inner SEI partial molar volume [m3.mol-1]": 9.585e-05,
    "Inner SEI reaction proportion": 0.5,
    "Lithium interstitial reference concentration [mol.m-3]": 15.0,
    "Lithium metal partial molar volume [m3.mol-1]": 1.3e-05,
    "Lithium plating transfer coefficient": 0.7,
    "Lower voltage cut-off [V]": 0.5,
    "Maximum concentration in negative electrode [mol.m-3]": 28746.0,
    "Maximum concentration in positive electrode [mol.m-3]": 35380.0,
    "Negative current collector conductivity [S.m-1]": 59600000.0,  # Cu foil
    "Negative current collector density [kg.m-3]": 8954.0,
    "Negative current collector specific heat capacity [J.kg-1.K-1]": 385.0,
    "Negative current collector surface heat transfer coefficient [W.m-2.K-1]": 0.0,
    "Negative current collector thermal conductivity [W.m-1.K-1]": 401.0,
    "Negative current collector thickness [m]": 2.5e-05,
    "Negative electrode Bruggeman coefficient (electrode)": 1.5,
    "Negative electrode Bruggeman coefficient (electrolyte)": 1.5,
    "Negative electrode active material volume fraction": 0.61,
    "Negative electrode charge transfer coefficient": 0.5,
    "Negative electrode conductivity [S.m-1]": 100.0,
    "Negative electrode density [kg.m-3]": 3100.0,
    "Negative electrode double-layer capacity [F.m-2]": 0.2,
    "Negative electrode porosity": 0.3,
    "Negative electrode reaction-driven LAM factor [m3.mol-1]": 0.0,
    "Negative electrode reference exchange-current density [A.m-2(m3.mol)1.5]": 1.061e-06,
    "Negative electrode specific heat capacity [J.kg-1.K-1]": 1100.0,
    "Negative electrode thermal conductivity [W.m-1.K-1]": 1.7,
    "Negative electrode thickness [m]": 6.2e-05,
    "Negative electrode transport efficiency": 0.16,
    "Negative particle radius [m]": 2.5e-06,
    "Negative tab heat transfer coefficient [W.m-2.K-1]": 0.0,
    "Nominal cell capacity [A.h]": 5.0,
    "Number of cells connected in series to make a battery": 1.0,
    "Number of electrodes connected in parallel to make a cell": 1.0,
    "Outer SEI open-circuit potential [V]": 0.8,
    "Outer SEI partial molar volume [m3.mol-1]": 9.585e-05,
    "Outer SEI solvent diffusivity [m2.s-1]": 2.5000000000000002e-22,
    "Positive current collector conductivity [S.m-1]": 35500000.0,  # Al foil
    "Positive current collector density [kg.m-3]": 2707.0,
    "Positive current collector specific heat capacity [J.kg-1.K-1]": 897.0,
    "Positive current collector surface heat transfer coefficient [W.m-2.K-1]": 0.0,
    "Positive current collector thermal conductivity [W.m-1.K-1]": 237.0,
    "Positive current collector thickness [m]": 2.5e-05,
    "Positive electrode Bruggeman coefficient (electrode)": 1.5,
    "Positive electrode Bruggeman coefficient (electrolyte)": 1.5,
    "Positive electrode active material volume fraction": 0.445,
    "Positive electrode charge transfer coefficient": 0.5,
    "Positive electrode conductivity [S.m-1]": 100.0,
    "Positive electrode density [kg.m-3]": 3100.0,
    "Positive electrode double-layer capacity [F.m-2]": 0.2,
    "Positive electrode porosity": 0.3,
    "Positive electrode reaction-driven LAM factor [m3.mol-1]": 0.0,
    "Positive electrode reference exchange-current density [A.m-2(m3.mol)1.5]": 4.824e-06,
    "Positive electrode specific heat capacity [J.kg-1.K-1]": 1100.0,
    "Positive electrode thermal conductivity [W.m-1.K-1]": 2.1,
    "Positive electrode thickness [m]": 6.7e-05,
    "Positive electrode transport efficiency": 0.16,
    "Positive particle radius [m]": 3.5e-06,
    "Positive tab heat transfer coefficient [W.m-2.K-1]": 0.0,
    "Ratio of lithium moles to SEI moles": 2.0,
    "Reference temperature [K]": 298.15,
    "SEI growth activation energy [J.mol-1]": 0.0,
    "SEI kinetic rate constant [m.s-1]": 1e-12,
    "SEI open-circuit potential [V]": 0.4,
    "SEI reaction exchange current density [A.m-2]": 1.5e-07,
    "SEI resistivity [Ohm.m]": 200000.0,
    "Separator Bruggeman coefficient (electrolyte)": 1.5,  # Usually 1.5 for porous media
    "Separator density [kg.m-3]": 397.0,  # Not sure about this one
    "Separator porosity": 0.39,
    "Separator specific heat capacity [J.kg-1.K-1]": 700.0,
    "Separator thermal conductivity [W.m-1.K-1]": 0.16,
    "Separator thickness [m]": 25e-6,
    "Separator transport efficiency ": 0.25,
    "Thermodynamic factor": 1.0,
    "Total heat transfer coefficient [W.m-2.K-1]": 5.0,
    "Typical lithium ion diffusivity [m2.s-1]": 5.34e-10,  # Within the range of 10^-10 to 10^-12 (For both Li and Na)
    "Typical plated lithium concentration [mol.m-3]": 1000.0,
    "Upper voltage cut-off [V]": 4.2,
}
